services:

  platform_docker-app:
    build: .
    container_name: miguel-app
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql://root:rootpassword@platform_docker-db:3306/app?serverVersion=8.0.32&charset=utf8mb4
    volumes:
      - ./:/var/www/html
    depends_on:
      - platform_docker-db

  platform_docker-db:
    image: mysql:8.0
    container_name: miguel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

  platform_docker-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: miguel-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: platform_docker-db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - platform_docker-db

volumes:
  database_data:
